# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-24 09:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='品名')),
                ('quantity', models.IntegerField(verbose_name='数量')),
                ('unit_price', models.PositiveIntegerField(verbose_name='単価')),
            ],
        ),
    ]
